# Generated by Django 5.2.9 on 2026-01-04 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20251216_0638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_image',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
